### PR TITLE
Add Search Devices Endpoint

### PR DESCRIPTION
**Pull request by kristinpeterson**
Add support for the [Search Devices endpoint](https://m2x.att.com/developer/documentation/v2/device#Search-Devices). Searching devices was previously done via the List Devices endpoint `/devices`, but now has it's own dedicated endpoint `/devices/search`. 

This issue has two parts:

1. Update the documentation for List Devices
2. Add support for Search Devices

Example of this update in the Ruby library: https://github.com/attm2x/m2x-ruby/commit/20e563d31e13dbca8771d10f856935dab7ee33cc

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@fsaravia this is ready for review

**Comment by fsaravia** [comment]
@kristinpeterson: Looks good! We definitely can reduce the duplication present in `JsonRequest` but I believe that's out of scope of this PR

**Comment by kristinpeterson** [comment]
@fsaravia ok, thanks!  Another thing we can discuss at the Summit :) I'd actually love to go over the `JSONRequest` file with you to see where we can trim it down some more. I had removed a great deal of duplication in a previous [PR](https://github.com/attm2x/m2x-android/pull/3), but would like to "pair program" with you on this one so that you can show me what areas I missed.

I think this should be a MAJOR version update, as it changes the method signature for the `searchDevices` method (adding JSONObject).

**Comment by fsaravia** [comment]
> I think this should be a MAJOR version update, as it changes the method signature for the searchDevices method (adding JSONObject).

Exactly :), but we can wait until all pending changes are made and do a release then :)

**Comment by kristinpeterson** [comment]
@fsaravia sounds good! I'm going to update the docs per your suggestion and then merge this PR.

**Pull request merged**
